### ISSUE TITLE
magellan missing some joined points?

### ISSUE THREAD

**Issue by geoHeil** [harsha2010/magellan#108] opened 2017-03-20 21:30 UTC
I am comparing geoSpark with magellan here https://github.com/geoHeil/geoSparkProblemJoinLoosingUserData. As I had some strange issues (losing the userData field of `jts.Geometry` objects after joins, not seeing points with same coordinates but different labels ) I started to compare geospark with Magellan. However whilst geospark will find at least a single join, Magellan will join no result whatsoever. What is wrong here? Is there a problem with the conversion to Magellan handlable geometry? Or am I using some fancy polygon edge case whilst joining?

The magellan sample is here https://github.com/geoHeil/geoSparkProblemJoinLoosingUserData/blob/master/src/main/scala/problemGeospark/Magellan.scala
and the data points here https://github.com/geoHeil/geoSparkProblemJoinLoosingUserData/tree/master/src/main/resources

**Comment by halfabrane** [comment] 2017-07-28 10:01
@geoHeil can you take a look at #130 ?
I am not able to reproduce the issue you mentioned here: I took your dataset and created a test case out of it. Maybe I am missing something?

**Comment by harsha2010** [comment] 2017-08-15 09:16
Cannot reproduce the issue , closing this. Please open a new one with a test case if it is still unresolved

**Closed by harsha2010** 2017-08-15 09:16 UTC
